/* 
**  mod_asdbTest.c -- Apache sample asdbTest module
**  [Autogenerated via ``apxs -n asdbTest -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_asdbTest.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /asdbTest in as follows:
**
**    #   apache2.conf
**    LoadModule asdbTest_module modules/mod_asdbTest.so
**    <Location /asdbTest>
**    SetHandler asdbTest
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /asdbTest and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/asdbTest 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_asdbTest.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include <apr_file_io.h>

#include <stdio.h>
#include <stdlib.h>


const char * MDTOOL = "markdown";

static int verbose = 01;
#define VERBOSE if( verbose )


#include "util.c"


static char* buildhtml( request_rec *r, const char* mdfile ){
	FILE *pp;

	char cmd[FILENAME_MAX];
	cmd[0] = 0;

	strcat ( cmd, MDTOOL );
	strcat ( cmd, " " );
	strcat ( cmd, mdfile );

	// open a pipe to markdown 
  	pp = popen(cmd, "r");

	// returning later an internal buffer is bad ...
	
	// this also not thread safe !!!

	// also output is limited in total to 60000 chars

	static char buf[60000];
	buf[0]=0;

	if (pp != NULL) {
		
		char line[8192];
		char *l = line;

		for(;;){
			l = fgets( l, sizeof line, pp );
			if( !l ) break;
			strncat ( buf, l, sizeof line-1 );
		}
			
		pclose(pp);
  	}	

	return buf;
}


/* The sample content handler */
static int asdbTest_handler(request_rec *r)
{

	if (strcmp(r->handler, "asdbtest")) {
		return DECLINED;
	}

	ap_set_content_type( r, "text/html" ); 

	VERBOSE{
		printheader( r );
	}

	char fnam [FILENAME_MAX];
	fnam[0]=0;
	strcat( fnam , r->filename );
	int len = strlen( fnam );

	// hack for apache file extension
	char* fpos = strstr( fnam, ".html" );
	if( fpos && &(fnam[len -5]) == fpos ){
		*fpos = 0;
	}
	strcat( fnam, ".md" );

	VERBOSE{
		ap_rprintf( r, "fnam %s\n", fnam );
	}

	char *md = buildhtml( r, fnam );
	ap_rprintf( r, "<br/>%s", md );

    return OK;
}


static void asdbTest_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(asdbTest_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA asdbTest_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    asdbTest_register_hooks  /* register hooks                      */
};



