/*
**  mod_apxscpp.c -- Apache sample apxscpp module
**  [Autogenerated via ``apxs -n apxscpp -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_apxscpp.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /apxscpp in as follows:
**
**    #   apache2.conf
**    LoadModule apxscpp_module modules/mod_apxscpp.so
**    <Location /apxscpp>
**    SetHandler apxscpp
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /apxscpp and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/apxscpp
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_apxscpp.c
*/

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include "http_log.h"


extern int thehandlerimpl(request_rec *r);


/* The sample content handler */
static int apxscpp_handler(request_rec *r)
{
    if (strcmp(r->handler, "apxscpp")) {
        return DECLINED;
    }

    ap_set_content_type( r, "text/html" );

    if ( r->header_only )
		return HTTP_NOT_IMPLEMENTED;

	thehandlerimpl( r );

	//ap_log_rerror( APLOG_MARK, 0, NULL, r , "%s", "request done" );

    return OK;
}

static void apxscpp_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(apxscpp_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA apxscpp_module = {
    STANDARD20_MODULE_STUFF,
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    apxscpp_register_hooks  /* register hooks                      */
};





