/* 
**  mod_asdbjs.c -- Apache sample asdbjs module
**  [Autogenerated via ``apxs -n asdbjs -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_asdbjs.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /asdbjs in as follows:
**
**    #   apache2.conf
**    LoadModule asdbjs_module modules/mod_asdbjs.so
**    <Location /asdbjs>
**    SetHandler asdbjs
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /asdbjs and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/asdbjs 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_asdbjs.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include <stdio.h>
#include <stdlib.h>


#define BLOCKSIZE 8192

void get_post_data( request_rec *r ){

 	int ret = ap_setup_client_block(r, REQUEST_CHUNKED_ERROR);

	if(OK == ret && ap_should_client_block(r))
	{
		char* buffer = (char*)apr_pcalloc(r->pool, BLOCKSIZE);

		int len;

		while((len=ap_get_client_block(r, buffer, BLOCKSIZE)) > 0)
		{
			// write data...
			buffer[len] = 0;
			ap_rprintf( r, "post data\n%s\n", buffer );

		}

	}

}


static int printitem(void *rec, const char *key, const char *value)
{
	request_rec *r = rec;
	ap_rprintf(r, "%s: %s\n", ap_escape_html(r->pool, key), ap_escape_html(r->pool, value));
	/* Zero would stop iterating; any other return value continues */
	return 1;
}

static void printheader(request_rec *r){
	ap_rprintf( r, "protocol %s\n", r->protocol );
	ap_rprintf( r, "uri %s\n", r->unparsed_uri );
	ap_rprintf( r, "path_info %s\n", r->path_info );
	ap_rprintf( r, "method %s\n", r->method );
	ap_rprintf( r, "useragent_ip %s\n", r->useragent_ip );
	ap_rprintf( r, "filename %s\n", r->filename );
   	ap_rprintf( r, "args %s\n", r->args );
   	ap_rprintf( r, "clength %s\n", r->clength );
   	ap_rprintf( r, "content_encoding %s\n", r->content_encoding );
   	ap_rprintf( r, "content_type %s\n", r->content_type );
   	ap_rprintf( r, "hostname %s\n", r->hostname );
   	ap_rprintf( r, "log_id %s\n", r->log_id );
   	ap_rprintf( r, "range %s\n", r->range );
   	ap_rprintf( r, "status_line %s\n", r->status_line );
   	ap_rprintf( r, "the_request %s\n", r->the_request );
   	ap_rprintf( r, "unparsed_uri %s\n", r->unparsed_uri );
   	ap_rprintf( r, "user %s\n", r->user );
   	ap_rprintf( r, "vlist_validator %s\n", r->vlist_validator );

	apr_array_header_t* header = apr_table_elts( r->headers_in ) ;
	ap_rprintf( r, "*headers_in\n");
	apr_table_do(printitem, r, r->headers_in, NULL);
}


static char* runjs( request_rec *r, const char* jsfile ){
	FILE *pp;

	char cmd[FILENAME_MAX];
	cmd[0] = 0;

	strcat ( cmd, "spidermonkeyjs" );
	strcat ( cmd, " " );
	strcat ( cmd, jsfile );

	if( r->args ){
		//strcat ( cmd, " -- " );
		strcat ( cmd, " '" );
		strcat ( cmd, r->args );
		strcat ( cmd, "'" );
	}

	// open a pipe to markdown 
  	pp = popen(cmd, "r");

	// returning later an internal buffer is bad ...
	
	// this also not thread safe !!!

	// also output is limited in total to 60000 chars

	static char buf[60000];
	buf[0]=0;

	if (pp != NULL) {

		strcat( buf, "opened pipe <br/>" );
		strcat( buf, "args " );	
		if( r->args )
			strcat( buf, r->args );	
		strcat( buf, "<br/>" );	
	
		char line[8192];
		char *l = line;

		for(;;){
			l = fgets( l, sizeof line, pp );
			if( !l ) break;
			strncat ( buf, l, sizeof line-1 );
		}
			
		pclose(pp);
  	}	
	else {
		strcat( buf, "calling js failed" );
	}

	return buf;
}





/* The sample content handler */
static int asdbjs_handler(request_rec *r)
{
    if (strcmp(r->handler, "asdbjs")) {
        return DECLINED;
    }
    r->content_type = "text/html";      


	char fnam [FILENAME_MAX];
	fnam[0]=0;
	strcat( fnam , r->filename );
	int len = strlen( fnam );

	// hack for apache file extension
	char* fpos = strstr( fnam, ".html" );
	if( fpos && &(fnam[len -5]) == fpos ){
		*fpos = 0;
	}
	strcat( fnam, ".js" );

	printheader( r );
	ap_rprintf( r, "running %s\n", fnam );    
	ap_rprintf( r, "path %s\n", getenv("PATH") );    

	if( M_POST == r->method_number ){
		get_post_data( r );
	}

	char *html = runjs( r, fnam );
	ap_rprintf( r, "<br/>%s", html );    


    return OK;
}

static void asdbjs_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(asdbjs_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA asdbjs_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    asdbjs_register_hooks  /* register hooks                      */
};



